# Copyright 2025 The Khronos Group, Inc.
# SPDX-License-Identifier: Apache-2.0

# Github CI file for the OpenCL-Guide
# This file is based heavily on the same file for the Vulkan-Guide.

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or manual dispatch
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: awesome_bot
        run: |
          gem install awesome_bot
          awesome_bot --allow-dupe chapters/*.md --white-list https://www.youtube.com/,https://github.com/KhronosGroup,https://github.com/microsoft
